name: Release zest tarball

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (for Yarn Berry)
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Pack zest
        working-directory: zest
        run: yarn pack --out ../zest.tgz

      - name: Show manifest used for packing
        working-directory: zest
        run: cat package.json

      - name: Show packed package.json
        run: tar -xOf zest.tgz package/package.json | grep '"bin"'

      - name: Upload zest tarball to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: zest.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
